import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NavbarDemo } from "@/components/Navbar";
import { SpeedInsights } from "@vercel/speed-insights/next";
import Mobilenav from "@/components/Mobilenav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <SpeedInsights/>
        <div className="hidden md:block">
        <NavbarDemo/>
        </div>
        <div className="block md:hidden">
          <Mobilenav/>
        </div>
        {children}</body>
    </html>
  );
}
